// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9hOemuBr0MJHtyxqxBLKq1hwo0jYtRRQ',
    appId: '1:415919379654:web:a2cc1788f467f42d78b3c7',
    messagingSenderId: '415919379654',
    projectId: 'cate-807ea',
    authDomain: 'cate-807ea.firebaseapp.com',
    storageBucket: 'cate-807ea.firebasestorage.app',
    measurementId: 'G-9X5EDLMTJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTYjkhUjQyoE4wO2D1DFgDdQi7AGN-Ikk',
    appId: '1:415919379654:android:a4f0ee391788c49978b3c7',
    messagingSenderId: '415919379654',
    projectId: 'cate-807ea',
    storageBucket: 'cate-807ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz1sAAGAlKz-tQW9AK_YvN_wWEQrTByss',
    appId: '1:415919379654:ios:c07268f9d2c7145278b3c7',
    messagingSenderId: '415919379654',
    projectId: 'cate-807ea',
    storageBucket: 'cate-807ea.firebasestorage.app',
    iosBundleId: 'com.cate.app',
  );
}
